# Default server block: Drop direct IP or unrecognized host requests
server {
    listen 80 default_server;
    server_name _;
    return 444; # Closes the connection immediately without response headers
}

# Domain specific server block
server {
    listen 80;
    server_name cipherlens.zeraynce.com;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Reverse proxy for API server endpoints
    location /api {
        proxy_pass http://backend:3005;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
